# SPDX-FileCopyrightText: 2021 Mikhail Zolotukhin <mail@genda.life>
#
# SPDX-License-Identifier: MIT

---
name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please 🔖
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: release-please-action

  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    env:
      DEBIAN_FRONTEND: noninteractive
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout Code 🛎️
        uses: actions/checkout@v2

      - name: Setup CI Utils ⚙️
        run: .github/scripts/utils-install.sh

      - name: Build 🔧
        run: |
          npm install
          .github/scripts/sysdep-install.sh
          cmake -S "." -B "build" -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX="$PWD/install-artifact"
          cmake --build "build"
          cmake --install "build"

      - name: Package 📦
        run: |
          tar czf install-artifact.tar.gz --directory=install-artifact .

      - name: Publish 🎉
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            install-artifact.tar.gz
